In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
data = pd.read_csv('cardekho.csv')

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB

In [11]:
print(data[data.duplicated()])

                                 name  year  selling_price  km_driven    fuel  \
13                      Maruti 800 AC  2007          60000      70000  Petrol
14           Maruti Wagon R LXI Minor  2007         135000      50000  Petrol
15               Hyundai Verna 1.6 SX  2012         600000     100000  Diesel
16             Datsun RediGO T Option  2017         250000      46000  Petrol
17              Honda Amaze VX i-DTEC  2014         450000     141000  Diesel
...                               ...   ...            ...        ...     ...
4307                 Mahindra Xylo H4  2019         599000      15000  Diesel
4308              Maruti Alto 800 LXI  2018         200000      35000  Petrol
4309                 Datsun GO Plus T  2017         350000      10171  Petrol
4310  Renault Duster 110PS Diesel RxL  2015         465000      41123  Diesel
4311          Toyota Camry Hybrid 2.5  2017        1900000      20118  Petrol

     seller_type transmission         owner
13    Individual       Manual   First Owner
14    Individual       Manual   First Owner
15    Individual       Manual   First Owner
16    Individual       Manual   First Owner
17    Individual       Manual  Second Owner
...          ...          ...           ...
4307  Individual       Manual   Third Owner
4308  Individual       Manual   First Owner
4309      Dealer       Manual   First Owner
4310      Dealer       Manual   First Owner
4311      Dealer    Automatic   First Owner

[763 rows x 8 columns]

In [15]:
df = pd.read_csv("Projects\Regression\data\cardekho_imputated.csv")

In [16]:
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [21]:
df.columns

Index(['model', 'vehicle_age', 'km_driven', 'seller_type', 'fuel_type',
       'transmission_type', 'mileage', 'engine', 'max_power', 'seats',
       'selling_price'],
      dtype='object')

In [18]:
df.drop(columns=['Unnamed: 0', 'car_name', 'brand'],axis=1,inplace=True)

In [20]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   model              15411 non-null  object
 1   vehicle_age        15411 non-null  int64
 2   km_driven          15411 non-null  int64
 3   seller_type        15411 non-null  object
 4   fuel_type          15411 non-null  object
 5   transmission_type  15411 non-null  object
 6   mileage            15411 non-null  float64
 7   engine             15411 non-null  int64
 8   max_power          15411 non-null  float64
 9   seats              15411 non-null  int64
 10  selling_price      15411 non-null  int64
dtypes: float64(2), int64(5), object(4)
memory usage: 1.3+ MB

In [28]:
df[df.duplicated()]

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
197,City,8,70000,Individual,Petrol,Manual,16.80,1497,116.30,5,545000
360,Baleno,2,5000,Individual,Petrol,Automatic,21.40,1197,83.10,5,686000
1353,Swift Dzire,4,50000,Individual,Diesel,Manual,28.40,1248,74.02,5,680000
1429,Wagon R,13,100000,Individual,Petrol,Manual,18.90,1061,67.00,5,150000
1485,i20,3,50000,Individual,Petrol,Manual,18.60,1197,81.83,5,625000
...,...,...,...,...,...,...,...,...,...,...,...
15229,Swift,8,80000,Individual,Diesel,Manual,22.90,1248,74.00,5,350000
15324,Wagon R,6,50000,Individual,CNG,Manual,26.60,998,58.16,5,450000
15367,Tiago,4,30000,Individual,Petrol,Manual,23.84,1199,84.00,5,350000
15378,Grand,6,30000,Individual,Petrol,Manual,18.90,1197,82.00,5,450000
15392,Rover,5,128000,Dealer,Diesel,Automatic,12.63,2179,147.50,5,2675000

In [29]:
df.drop_duplicates(inplace=True)

In [30]:
df

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...
15406,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
15407,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
15408,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15409,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15410,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [31]:
df['fuel_type'].dtype

dtype('O')

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15244 entries, 0 to 15410
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   model              15244 non-null  object
 1   vehicle_age        15244 non-null  int64
 2   km_driven          15244 non-null  int64
 3   seller_type        15244 non-null  object
 4   fuel_type          15244 non-null  object
 5   transmission_type  15244 non-null  object
 6   mileage            15244 non-null  float64
 7   engine             15244 non-null  int64
 8   max_power          15244 non-null  float64
 9   seats              15244 non-null  int64
 10  selling_price      15244 non-null  int64
dtypes: float64(2), int64(5), object(4)
memory usage: 1.4+ MB

In [36]:
categ = [i for i in df.columns if df[i].dtype == 'O']
num = [i for i in df.columns if df[i].dtype != 'O']

In [44]:
categ

['model', 'seller_type', 'fuel_type', 'transmission_type']

In [39]:
[df[i].unique().size for i in num]

[24, 3688, 411, 110, 342, 8, 1086]

In [41]:
dis = ['vehicle_age','seats']

### NUmerical type has two kinds discrete and continuous

In [42]:
x = df.drop(['selling_price'],axis=1)
y = df['selling_price']

In [51]:
[i for i in categ if i != 'model']

['seller_type', 'fuel_type', 'transmission_type']

In [59]:
num

['vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats']

In [53]:
x

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5
...,...,...,...,...,...,...,...,...,...,...
15406,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5
15407,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7
15408,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5
15409,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7
15410,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5

In [66]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
std = StandardScaler()
lab = LabelEncoder()
ohe = OneHotEncoder(drop='first')
col = ColumnTransformer([('one hot',ohe,[i for i in categ if i != 'model']),
                        # ('label',lab,['model']),
                        ('scalar',std,num)],
                        remainder= 'passthrough')

In [64]:
x['model'] = lab.fit_transform(x['model'])

In [67]:
x = col.fit_transform(x)

In [71]:
x = pd.DataFrame(x)

In [72]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=45,)

In [73]:
x_train

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
10945,1.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.339840,-0.900994,0.408395,-0.555669,-0.407968,-0.403299,13.0
8095,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-0.676739,-0.091425,1.653247,-0.457668,-0.620019,-0.403299,89.0
13790,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.317914,0.200145,-0.865240,0.977760,1.943231,-0.403299,104.0
13890,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.312566,1.822875,0.768179,-0.457668,-0.620019,-0.403299,88.0
739,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.317914,1.243329,-1.829460,2.845545,3.280781,2.069705,74.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11808,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.975668,0.774302,0.158945,-0.555669,-0.505838,-0.403299,117.0
6012,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.644117,-0.881676,-1.037936,-0.557591,-0.643321,-0.403299,39.0
13955,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.981015,-0.456675,-0.291984,0.977760,1.780115,-0.403299,1.0
6558,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.676739,-0.302129,-0.371137,-0.553748,-0.433600,0.833203,62.0
7115,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.345188,0.432949,0.276474,-0.555669,-0.407036,-0.403299,89.0

In [87]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression,RidgeCV,LassoCV
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import root_mean_squared_error,r2_score,mean_absolute_error

In [88]:
def evalu(pred,truth):
    print("rmse: ",root_mean_squared_error(truth,pred))
    print("r2 score: ",r2_score(truth,pred))
    print("mae: ",mean_absolute_error(truth,pred))

In [86]:
models = {
    "RandomForest" : RandomForestRegressor(),
    "LinearRegression" : LinearRegression(),
    "Ridge regression" : RidgeCV(),
    "Lasso regression" : LassoCV(),
    "k neighbors" : KNeighborsRegressor(),
    "Decision regressor" : DecisionTreeRegressor()
}

In [ ]:
models.val

In [92]:
for i in range (0,len(list(models))):
    model = list(models.values())[i]
    model.fit(x_train,y_train)
    y_pred = model.predict(x_test)
    print("*" * 35)
    print("\n")
    print(model)
    evalu(y_pred,y_test)

***********************************


RandomForestRegressor()
rmse:  190074.6057490724
r2 score:  0.9448634251332149
mae:  95832.99368157171
***********************************


LinearRegression()
rmse:  455464.90636965167
r2 score:  0.6834069130724238
mae:  271678.6693838645
***********************************


RidgeCV()
rmse:  455341.2004640074
r2 score:  0.6835788653584983
mae:  271401.51875096344
***********************************


LassoCV()
rmse:  456956.38947916444
r2 score:  0.681330062073322
mae:  270596.71357877477
***********************************


KNeighborsRegressor()
rmse:  247397.71815119244
r2 score:  0.9065922380681884
mae:  102848.38471630042
***********************************


DecisionTreeRegressor()
rmse:  254682.32868200194
r2 score:  0.9010104815669624
mae:  124208.78469131175

In [ ]:
#